### ISSUE TITLE
main.py 运行失败

### ISSUE THREAD

**Issue by wutea7** [kaedea/notion-down#24]
Linux 版本: Debian 10
Python 版本: 2.7.16
NotionDown 版本: 最新 master 分支

**运行命令**

```bash
python main.py \
--blog_url https://like-plum-3be.notion.site/NotionDown-Posts-Template-2af05230e0c14c8094d7665e4b954ad5 \
--token_v2 xxxxxxxxxxx
```

**运行结果**

```bash
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from notion_reader import NotionReader
  File "/root/notion-down/notion_reader.py", line 21
    def get_client() -> NotionClient:
                     ^
SyntaxError: invalid syntax
```

不清楚是哪里出了问题

**Comment by kaedea** [comment]
@wutea7  使用 Python3.7

**Comment by wutea7** [comment]
更换 Python 3.7 后变成这样了

```bash
Hello, NotionDown!

Run with configs:
config = {
  "debuggable": true,
  "workspace": "/root/notion-down",
  "output": "/root/notion-down/build",
  "writer": "notion",
  "channels": [
    "default"
  ],
  "page_titles": [
    "all"
  ],
  "token_v2": "xxx",
  "blog_url": "https://like-plum-3be.notion.site/NotionDown-Posts-Template-2af05230e0c14c8094d7665e4b954ad5"
}
#handle_post
read all pages from main page
#read_main_page
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/notion/utils.py", line 37, in extract_id
    return str(uuid.UUID(url_or_id))
  File "/usr/lib/python3.7/uuid.py", line 160, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 29, in <module>
    start()
  File "main.py", line 10, in start
    notion_pages = NotionReader.handle_post()
  File "/root/notion-down/notion_reader.py", line 31, in handle_post
    page_blocks = NotionReader._read_post_pages()
  File "/root/notion-down/notion_reader.py", line 79, in _read_post_pages
    main_page = NotionReader.read_main_page()
  File "/root/notion-down/notion_reader.py", line 64, in read_main_page
    raise e
  File "/root/notion-down/notion_reader.py", line 59, in read_main_page
    return NotionReader.get_client().get_block(Config.blog_url())
  File "/usr/local/lib/python3.7/dist-packages/notion/client.py", line 168, in get_block
    block_id = extract_id(url_or_id)
  File "/usr/local/lib/python3.7/dist-packages/notion/utils.py", line 39, in extract_id
    raise InvalidNotionIdentifier(input_value)
notion.utils.InvalidNotionIdentifier: https://like-plum-3be.notion.site/NotionDown-Posts-Template-2af05230e0c14c8094d7665e4b954ad5
```

**Comment by kaedea** [comment]
> 更换 Python 3.7 后变成这样了
> 
> ```python
> Hello, NotionDown!
> 
> Run with configs:
> config = {
>   "debuggable": true,
>   "workspace": "/root/notion-down",
>   "output": "/root/notion-down/build",
>   "writer": "notion",
>   "channels": [
>     "default"
>   ],
>   "page_titles": [
>     "all"
>   ],
>   "token_v2": "xxx",
>   "blog_url": "https://like-plum-3be.notion.site/NotionDown-Posts-Template-2af05230e0c14c8094d7665e4b954ad5"
> }
> #handle_post
> read all pages from main page
> #read_main_page
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/notion/utils.py", line 37, in extract_id
>     return str(uuid.UUID(url_or_id))
>   File "/usr/lib/python3.7/uuid.py", line 160, in __init__
>     raise ValueError('badly formed hexadecimal UUID string')
> ValueError: badly formed hexadecimal UUID string
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main.py", line 29, in <module>
>     start()
>   File "main.py", line 10, in start
>     notion_pages = NotionReader.handle_post()
>   File "/root/notion-down/notion_reader.py", line 31, in handle_post
>     page_blocks = NotionReader._read_post_pages()
>   File "/root/notion-down/notion_reader.py", line 79, in _read_post_pages
>     main_page = NotionReader.read_main_page()
>   File "/root/notion-down/notion_reader.py", line 64, in read_main_page
>     raise e
>   File "/root/notion-down/notion_reader.py", line 59, in read_main_page
>     return NotionReader.get_client().get_block(Config.blog_url())
>   File "/usr/local/lib/python3.7/dist-packages/notion/client.py", line 168, in get_block
>     block_id = extract_id(url_or_id)
>   File "/usr/local/lib/python3.7/dist-packages/notion/utils.py", line 39, in extract_id
>     raise InvalidNotionIdentifier(input_value)
> notion.utils.InvalidNotionIdentifier: https://like-plum-3be.notion.site/NotionDown-Posts-Template-2af05230e0c14c8094d7665e4b954ad5
> ```

看着像是你的 blog_url 格式有问题，换个不带自定义域名的链接试试吧。

**Comment by wutea7** [comment]
把 blog_url 改成 https://www.notion.so/page_id 后好了，感谢
